name: user_articles
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.1
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0

  


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^2.3.2
  retrofit_generator: ^5.0.0
  injectable_generator: ^2.1.4




flutter:
  uses-material-design: true
